//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.07 at 10:53:07 PM EST 
//


package com.acp.process;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ruleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ruleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="onEvent" type="{http://www.swin.edu.au}onEventType"/>
 *         &lt;element name="preCon" type="{http://www.swin.edu.au}preconType"/>
 *         &lt;element name="do" type="{http://www.swin.edu.au}doType"/>
 *         &lt;element name="postCon" type="{http://www.swin.edu.au}postconType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ruleType", propOrder = {
    "onEvent",
    "preCon",
    "_do",
    "postCon"
})
public class RuleType {

    @XmlElement(namespace = "http://www.swin.edu.au", required = true)
    protected OnEventType onEvent;
    @XmlElement(namespace = "http://www.swin.edu.au", required = true)
    protected PreconType preCon;
    @XmlElement(name = "do", namespace = "http://www.swin.edu.au", required = true)
    protected DoType _do;
    @XmlElement(namespace = "http://www.swin.edu.au", required = true)
    protected PostconType postCon;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the onEvent property.
     * 
     * @return
     *     possible object is
     *     {@link OnEventType }
     *     
     */
    public OnEventType getOnEvent() {
        return onEvent;
    }

    /**
     * Sets the value of the onEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnEventType }
     *     
     */
    public void setOnEvent(OnEventType value) {
        this.onEvent = value;
    }

    /**
     * Gets the value of the preCon property.
     * 
     * @return
     *     possible object is
     *     {@link PreconType }
     *     
     */
    public PreconType getPreCon() {
        return preCon;
    }

    /**
     * Sets the value of the preCon property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreconType }
     *     
     */
    public void setPreCon(PreconType value) {
        this.preCon = value;
    }

    /**
     * Gets the value of the do property.
     * 
     * @return
     *     possible object is
     *     {@link DoType }
     *     
     */
    public DoType getDo() {
        return _do;
    }

    /**
     * Sets the value of the do property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoType }
     *     
     */
    public void setDo(DoType value) {
        this._do = value;
    }

    /**
     * Gets the value of the postCon property.
     * 
     * @return
     *     possible object is
     *     {@link PostconType }
     *     
     */
    public PostconType getPostCon() {
        return postCon;
    }

    /**
     * Sets the value of the postCon property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostconType }
     *     
     */
    public void setPostCon(PostconType value) {
        this.postCon = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
