//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.28 at 04:09:42 PM EST 
//


package com.acp.sharingrule;
/*
 *  @version 1.1
 */

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ruleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ruleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="when" type="{http://www.swin.edu.au}whenType"/>
 *         &lt;element name="share" type="{http://www.swin.edu.au}shareType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="no" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ruleType", propOrder = {
    "when",
    "share"
})
public class RuleType {

    @XmlElement(namespace = "http://www.swin.edu.au", required = true)
    protected WhenType when;
    @XmlElement(namespace = "http://www.swin.edu.au", required = true)
    protected ShareType share;
    @XmlAttribute(required = true)
    protected String no;

    /**
     * Gets the value of the when property.
     * 
     * @return
     *     possible object is
     *     {@link WhenType }
     *     
     */
    public WhenType getWhen() {
        return when;
    }

    /**
     * Sets the value of the when property.
     * 
     * @param value
     *     allowed object is
     *     {@link WhenType }
     *     
     */
    public void setWhen(WhenType value) {
        this.when = value;
    }

    /**
     * Gets the value of the share property.
     * 
     * @return
     *     possible object is
     *     {@link ShareType }
     *     
     */
    public ShareType getShare() {
        return share;
    }

    /**
     * Sets the value of the share property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShareType }
     *     
     */
    public void setShare(ShareType value) {
        this.share = value;
    }

    /**
     * Gets the value of the no property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNo() {
        return no;
    }

    /**
     * Sets the value of the no property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNo(String value) {
        this.no = value;
    }

}
